apiVersion: v1
kind: Namespace
metadata:
  name: frontend-ns
  labels:
    tier: frontend
---
apiVersion: v1
kind: Namespace
metadata:
  name: backend-ns
  labels:
    tier: backend
---
apiVersion: v1
kind: Namespace
metadata:
  name: database-ns
  labels:
    tier: database
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: frontend-quota
  namespace: frontend-ns
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "500Mi"
    limits.cpu: "2"
    limits.memory: "1Gi"
    pods: "5"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: backend-quota
  namespace: backend-ns
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "500Mi"
    limits.cpu: "2"
    limits.memory: "1Gi"
    pods: "5"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: database-quota
  namespace: database-ns
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "500Mi"
    limits.cpu: "2"
    limits.memory: "1Gi"
    pods: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
    name: frontend-lr
    namespace: frontend-ns
spec:
    limits:
    - max:
        cpu: 200m
        memory: 100Mi
      min:
        cpu: 100m
        memory: 50Mi
      default:
        cpu: "150m"
        memory: 75Mi
      defaultRequest:
        cpu: "150m"
        memory: 75Mi
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
    name: backend-lr
    namespace: backend-ns
spec:
    limits:
    - max:
        cpu: 200m
        memory: 100Mi
      min:
        cpu: 100m
        memory: 50Mi
      default:
        cpu: 150m
        memory: 75Mi
      defaultRequest:
        cpu: 150m
        memory: 75Mi
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
    name: database-lr
    namespace: database-ns
spec:
    limits:
    - max:
        cpu: 200m
        memory: 100Mi
      min:
        cpu: 100m
        memory: 50Mi
      default:
        cpu: 150m
        memory: 75Mi
      defaultRequest:
        cpu: 150m
        memory: 75Mi
      type: Container




