apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: attend-frontend-hpa
  namespace: frontend-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: attend-frontend-deploy
  minReplicas: 1
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 100 # 결정 100초
      policies:
      - type: Pods
        value: 1
        periodSeconds: 10 # 메트릭 평가 수집 10초
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: attend-backend-hpa
  namespace: backend-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: attend-backend-deploy
  minReplicas: 1
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 100 # 결정 100초
      policies:
      - type: Pods
        value: 1
        periodSeconds: 10 # 메트릭 평가 수집 10초
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: qa-frontend-hpa
  namespace: frontend-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qa-frontend-deploy
  minReplicas: 1
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 100 # 결정 100초
      policies:
      - type: Pods
        value: 1
        periodSeconds: 10 # 메트릭 평가 수집 10초
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: qa-backend-hpa
  namespace: backend-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qa-backend-deploy
  minReplicas: 1
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 100 # 결정 100초
      policies:
      - type: Pods
        value: 1
        periodSeconds: 10 # 메트릭 평가 수집 10초
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
